name: flutter_adyen
description: Flutter plugin to integrate Adyen DropIn UI for Android and iOS.
version: 0.4.2
authors: [Benjamin Baumann <benjamin.baumann@intive.com>]
homepage: https://github.com/intive-opensource/adyen_flutter

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: app.adyen.flutter_adyen
    pluginClass: FlutterAdyenPlugin

