name: adyen_dropin
description: Flutter plugin to integrate Adyen DropIn UI for Android and iOS.
version: 0.6.0
homepage: https://github.com/intive-opensource/adyen_flutter

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      androidPackage: app.adyen.flutter_adyen
      pluginClass: FlutterAdyenPlugin

